dist: xenial
language: python
cache: pip
python:
  - 3.7
install:
  - pip install .
  - pip install flake8
script:
  - flake8 wtl
notifications:
  email: false
  slack:
    secure: obav/44HcU5BgPXdhH8Gi3Fc9tGlxBXV10X6C3rtI3GVxt5w0QIXeKjexBuvr8jbodeN6XUmrFZ1AA1pjkEAAxmUw4Vz+PL9l1w2Cz2+o1oI0/585loTfNdMtNlm7qxtNaA8wlalwlrUtkwBlDpjh+V9NWAdjfizXmaxhze9gXs2BnYd6R2bF7nPc2KFzu/0E/0UusLP3HlaIsBlHzwhKJQAQw2uHFNY7uQ2h13yoRgYjWSaF6B1cpmYNnfSsi/DPfpHLCPGGYvzjsCm5JiAY/ISz27TprHknhymiIAL9fHRe7IpW8WncTvp4OUtDjz68qkEl4JymJk0VEWiFrmUUC6xpZYLbD/opYyjGv59zzlx3uYqe7fayDF5NO3dEgbQOaC7bnVFBLllcgBLhtiOZlNVJOXr/pC8AJKbcaqojWIKD+jE2mt4puyLb3PAaKJ7K+dmuirBaTeEoes7rYI5suhrkDmFr/ALjPVe28nSof3zVS8gvjr9Cxws9XV6k+BEdNF+AsJ1IOIBvwD5kWsrEenpKFIW1WUOtkFlvoOln/vwb8A8yRYVTUSFSC/Wl2Y4NJVUJ8BeFvFqs9ViYCtcZlNaDBQkXFNNGP8A1zIFOFjiWJ3rCGozX48btRy+MUAVMk1tVlg+kWULmS/AqNClsJEa4xB9Bl95UwLX9UHoxWQ=
