on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pip
      run: python -m pip install -U pip
    - name: Install this
      run: python -m pip install -U .[dev]
    - name: flake8
      run: python -m pflake8 . --count --show-source --statistics
    - uses: psf/black@stable
    - name: Install
      run: pip install .
