name: flake8

on: [push]

jobs:
  flake8:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install flake8
    - name: Lint with flake8
      run: flake8 . --count --show-source --statistics
    - name: Install
      run: pip install .
