on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
        cache: 'pip'
    - name: Install this
      run: python -m pip install -U .[dev]
    - name: Lint
      run: python -m ruff check .
    - name: Format
      run: python -m ruff format --diff .
