on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install this
      run: python -m pip install -U .[dev]
    - name: Lint
      run: python -m ruff check .
    - name: Format
      run: python -m ruff format --diff .
